### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by zoubinok** [fanglab/mbin#6]
* mbin version: 1.1.0
* Python version: 2.7.3
* Operating System: Ubuntu 12.04 LTS

### Description
Dear sir,
I used the virtual environment and installed thses packages:
backports.functools-lru-cache (1.5)
biopython (1.70)
cycler (0.10.0)
Cython (0.28)
h5py (2.7.1)
kiwisolver (1.0.1)
matplotlib (2.2.0)
mbin (1.1.0)
numpy (1.13.3)
pbcore (1.2.10)
pip (9.0.2)
pyparsing (2.2.0)
pysam (0.14)
python-dateutil (2.7.0)
pytz (2018.3)
scipy (1.0.0)
setuptools (38.6.0)
six (1.11.0)
subprocess32 (3.2.7)
wheel (0.30.0)

I want to use buildcontrols. And I used data in the github. But something is wrong. Would you like to help me? Thank you.

### What I Did
(venv) zoubinserver@ubuntuZ:~/mbin/mbin/data$ buildcontrols -i aligned_reads.cmp.h5 
Traceback (most recent call last):
  File "/home/zoubinserver/venv/bin/buildcontrols", line 11, in <module>
    sys.exit(launch())
  File "/home/zoubinserver/venv/local/lib/python2.7/site-packages/mbin/controls.py", line 17, in launch
    opts,control_aln_fn = __parseArgs()
  File "/home/zoubinserver/venv/local/lib/python2.7/site-packages/mbin/controls.py", line 206, in __parseArgs
    opts.ref              = os.path.abspath(opts.ref)
  File "/home/zoubinserver/venv/lib/python2.7/posixpath.py", line 343, in abspath
    if not isabs(path):
  File "/home/zoubinserver/venv/lib/python2.7/posixpath.py", line 53, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
(venv) zoubinserver@ubuntuZ:~/mbin/mbin/data$ buildcontrols m140905_042212_sidney_c100564852550000001823085912221377_s1_X0.aligned_subreads.cmp.h5 
Traceback (most recent call last):
  File "/home/zoubinserver/venv/bin/buildcontrols", line 11, in <module>
    sys.exit(launch())
  File "/home/zoubinserver/venv/local/lib/python2.7/site-packages/mbin/controls.py", line 17, in launch
    opts,control_aln_fn = __parseArgs()
  File "/home/zoubinserver/venv/local/lib/python2.7/site-packages/mbin/controls.py", line 206, in __parseArgs
    opts.ref              = os.path.abspath(opts.ref)
  File "/home/zoubinserver/venv/lib/python2.7/posixpath.py", line 343, in abspath
    if not isabs(path):
  File "/home/zoubinserver/venv/lib/python2.7/posixpath.py", line 53, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by jbeaulaurier** [comment]
Hello,

Sorry about that. This should be fixed with 7263defd6c7ecc78da48d1fa6fa06ef6273c652c. Let me know if you encounter any additional problems.

Thanks,
John

**Comment by zoubinok** [comment]
Hello, I tried again. New bugs appear.
So I am wandering if I used the right input file. Have you offer the wga_aligned_reads.cmp.h5?
The first warning is : 

2018-03-25 13:44:41 [WARNING] Failed command: cut -d$'\t' -f14295-16336 control_ipds.tmp > control_ipds.tmp.sub.7

But interestingly, I can run it in the terminal directly. 


(venv) zoubinserver@ubuntuZ:~/mbin/mbin/data$ buildcontrols -i --procs=4 --control_pkl_name=control_means.pkl aligned_reads.cmp.h5
2018-03-25 13:42:06 [INFO] Initiating dictionary of all possible motifs...
2018-03-25 13:42:06 [INFO]   - Adding 256 4-mer motifs...
2018-03-25 13:42:06 [INFO] Done: 256 possible contiguous motifs

2018-03-25 13:42:06 [INFO]   - Adding 1024 5-mer motifs...
2018-03-25 13:42:06 [INFO] Done: 1536 possible contiguous motifs

2018-03-25 13:42:06 [INFO]   - Adding 4096 6-mer motifs...
2018-03-25 13:42:06 [INFO] Done: 7680 possible contiguous motifs

2018-03-25 13:42:06 [INFO]   - Adding bipartite motifs to search space...
2018-03-25 13:42:07 [INFO] Done: 194560 possible bipartite motifs

2018-03-25 13:42:07 [INFO] 
2018-03-25 13:42:07 [INFO] Preparing to create new control data in ctrl_tmp
2018-03-25 13:42:07 [INFO] Loading data from /home/zoubinserver/mbin/mbin/data/aligned_reads.cmp.h5...
2018-03-25 13:42:07 [INFO] Querying 246 reads using 4 chunks of size 61...
2018-03-25 13:42:07 [INFO] ...chunk 0	- mol 0/61 (0.0%)
2018-03-25 13:42:08 [INFO] ...chunk 1	- mol 0/61 (0.0%)
2018-03-25 13:42:09 [INFO] ...chunk 2	- mol 0/61 (0.0%)
2018-03-25 13:42:10 [INFO] ...chunk 3	- mol 0/61 (0.0%)
2018-03-25 13:42:17 [INFO] ...chunk 0	- mol 6/61 (9.0%)
2018-03-25 13:42:18 [INFO] ...chunk 1	- mol 6/61 (9.0%)
2018-03-25 13:42:19 [INFO] ...chunk 2	- mol 6/61 (9.0%)
2018-03-25 13:42:20 [INFO] ...chunk 3	- mol 6/61 (9.0%)
2018-03-25 13:42:38 [INFO] ...chunk 0	- mol 12/61 (19.0%)
2018-03-25 13:42:38 [INFO] ...chunk 1	- mol 12/61 (19.0%)
2018-03-25 13:42:39 [INFO] ...chunk 2	- mol 12/61 (19.0%)
2018-03-25 13:42:40 [INFO] ...chunk 3	- mol 12/61 (19.0%)
2018-03-25 13:42:47 [INFO] ...chunk 0	- mol 18/61 (29.0%)
2018-03-25 13:42:48 [INFO] ...chunk 1	- mol 18/61 (29.0%)
2018-03-25 13:42:49 [INFO] ...chunk 2	- mol 18/61 (29.0%)
2018-03-25 13:42:49 [INFO] ...chunk 3	- mol 18/61 (29.0%)
2018-03-25 13:43:06 [INFO] ...chunk 0	- mol 24/61 (39.0%)
2018-03-25 13:43:07 [INFO] ...chunk 1	- mol 24/61 (39.0%)
2018-03-25 13:43:08 [INFO] ...chunk 2	- mol 24/61 (39.0%)
2018-03-25 13:43:08 [INFO] ...chunk 3	- mol 24/61 (39.0%)
2018-03-25 13:43:25 [INFO] ...chunk 0	- mol 30/61 (49.0%)
2018-03-25 13:43:26 [INFO] ...chunk 1	- mol 30/61 (49.0%)
2018-03-25 13:43:27 [INFO] ...chunk 3	- mol 30/61 (49.0%)
2018-03-25 13:43:27 [INFO] ...chunk 2	- mol 30/61 (49.0%)
2018-03-25 13:43:35 [INFO] ...chunk 1	- mol 36/61 (59.0%)
2018-03-25 13:43:36 [INFO] ...chunk 0	- mol 36/61 (59.0%)
2018-03-25 13:43:36 [INFO] ...chunk 3	- mol 36/61 (59.0%)
2018-03-25 13:43:37 [INFO] ...chunk 2	- mol 36/61 (59.0%)
2018-03-25 13:43:55 [INFO] ...chunk 1	- mol 42/61 (68.0%)
2018-03-25 13:43:56 [INFO] ...chunk 3	- mol 42/61 (68.0%)
2018-03-25 13:43:56 [INFO] ...chunk 0	- mol 42/61 (68.0%)
2018-03-25 13:43:56 [INFO] ...chunk 2	- mol 42/61 (68.0%)
2018-03-25 13:44:05 [INFO] ...chunk 1	- mol 48/61 (78.0%)
2018-03-25 13:44:05 [INFO] ...chunk 3	- mol 48/61 (78.0%)
2018-03-25 13:44:06 [INFO] ...chunk 0	- mol 48/61 (78.0%)
2018-03-25 13:44:06 [INFO] ...chunk 2	- mol 48/61 (78.0%)
2018-03-25 13:44:24 [INFO] ...chunk 1	- mol 54/61 (88.0%)
2018-03-25 13:44:25 [INFO] ...chunk 3	- mol 54/61 (88.0%)
2018-03-25 13:44:26 [INFO] ...chunk 2	- mol 54/61 (88.0%)
2018-03-25 13:44:30 [INFO] Chunk 0: found 55 alignments (54 molecules) > 100bp in aligned_reads.cmp.h5
2018-03-25 13:44:31 [INFO] Chunk 3: found 55 alignments (55 molecules) > 100bp in aligned_reads.cmp.h5
2018-03-25 13:44:32 [INFO] Chunk 2: found 55 alignments (55 molecules) > 100bp in aligned_reads.cmp.h5
2018-03-25 13:44:33 [INFO] Chunk 1: found 58 alignments (58 molecules) > 100bp in aligned_reads.cmp.h5
2018-03-25 13:44:33 [INFO] Combining results data from all chunks...
2018-03-25 13:44:33 [INFO] ...1/4
2018-03-25 13:44:33 [INFO] ...2/4
2018-03-25 13:44:33 [INFO] ...3/4
2018-03-25 13:44:33 [INFO] ...4/4
2018-03-25 13:44:33 [INFO] Done.
2018-03-25 13:44:33 [INFO] Catting contig-specific data from parallel processes...
2018-03-25 13:44:33 [INFO] ...contig plasmid_phel3 (0/1)
2018-03-25 13:44:38 [INFO] Done.
2018-03-25 13:44:38 [INFO] 
2018-03-25 13:44:38 [INFO] Building dictionary of control values for all motifs...
2018-03-25 13:44:38 [INFO]    * Initial build requires significant time and memory.
2018-03-25 13:44:41 [INFO]   - Control data: chunk 1/100
2018-03-25 13:44:41 [INFO]   - Control data: chunk 8/100
2018-03-25 13:44:41 [INFO]   - Control data: chunk 15/100
2018-03-25 13:44:41 [INFO]   - Control data: chunk 22/100
2018-03-25 13:44:41 [WARNING] Failed command: cut -d$'\t' -f14295-16336 control_ipds.tmp > control_ipds.tmp.sub.7
2018-03-25 13:44:41 [WARNING] Failed command: cut -d$'\t' -f1-2042 control_ipds.tmp > control_ipds.tmp.sub.0
2018-03-25 13:44:41 [WARNING] Failed command: cut -d$'\t' -f42883-44924 control_ipds.tmp > control_ipds.tmp.sub.21
2018-03-25 13:44:41 [WARNING] Failed command: cut -d$'\t' -f28589-30630 control_ipds.tmp > control_ipds.tmp.sub.14
2018-03-25 13:44:41 [WARNING] Failed command: cut -d$'\t' -f1-2042 control_ipdsN.tmp > control_ipdsN.tmp.sub.0
Traceback (most recent call last):
  File "/home/zoubinserver/mbin2/venv/bin/buildcontrols", line 11, in <module>
    load_entry_point('mbin==1.1.1', 'console_scripts', 'buildcontrols')()
  File "/home/zoubinserver/mbin2/venv/local/lib/python2.7/site-packages/mbin-1.1.1-py2.7.egg/mbin/controls.py", line 20, in launch
2018-03-25 13:44:41 [WARNING] Failed command: cut -d$'\t' -f42883-44924 control_ipdsN.tmp > control_ipdsN.tmp.sub.21
2018-03-25 13:44:41 [WARNING] Failed command: cut -d$'\t' -f14295-16336 control_ipdsN.tmp > control_ipdsN.tmp.sub.7
2018-03-25 13:44:41 [WARNING] Failed command: cut -d$'\t' -f28589-30630 control_ipdsN.tmp > control_ipdsN.tmp.sub.14
2018-03-25 13:44:41 [INFO]   - Control data: chunk 29/100
2018-03-25 13:44:41 [WARNING] Failed command: cut -d$'\t' -f57177-59218 control_ipds.tmp > control_ipds.tmp.sub.28
2018-03-25 13:44:41 [WARNING] Failed command: cut -d$'\t' -f57177-59218 control_ipdsN.tmp > control_ipdsN.tmp.sub.28
    extract_controls(opts, control_aln_fn)
  File "/home/zoubinserver/mbin2/venv/local/lib/python2.7/site-packages/mbin-1.1.1-py2.7.egg/mbin/controls.py", line 55, in extract_controls
    control_means    = controls.build_control_IPD_dict(motifs, bi_motifs)
  File "/home/zoubinserver/mbin2/venv/local/lib/python2.7/site-packages/mbin-1.1.1-py2.7.egg/mbin/controls.py", line 488, in build_control_IPD_dict
    control_means,not_found = self.chunk_control_matrices(control_ipds_fn[0], control_ipds_N_fn[0], control_kmers_fn[0])
  File "/home/zoubinserver/mbin2/venv/local/lib/python2.7/site-packages/mbin-1.1.1-py2.7.egg/mbin/controls.py", line 406, in chunk_control_matrices
    results = mbin.launch_pool(self.opts.procs, process_contig_chunk, args)
  File "/home/zoubinserver/mbin2/venv/local/lib/python2.7/site-packages/mbin-1.1.1-py2.7.egg/mbin/mbin.py", line 40, in launch_pool
    results = p.map(funct, args)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 227, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 528, in get
    raise self._value
UserWarning: loadtxt: Empty input file: "control_ipds.tmp.sub.0"
(venv) zoubinserver@ubuntuZ:~/mbin/mbin/data$  cd ctrl_tmp/
(venv) zoubinserver@ubuntuZ:~/mbin/mbin/data/ctrl_tmp$ cut -d$'\t' -f14295-16336 control_ipds.tmp > control_ipds.tmp.sub.7

**Comment by zoubinok** [comment]
Hello, 
I used CentOS to run it today. And I  find that everything is OK. So I think it do not support Ubuntu well.
